language: ruby
rvm:
    - "2.3.1"
env:
    - DB=postgresql
script:
    - bundle exec rake db:test:prepare
before_install:
    - cd travel_code
    - cp config/database.travis.yml config/database.yml
    - psql -c 'create database mydb_test' -U postgres
before_script:
    - cd travel_code/config
    - openssl aes-256-cbc -K $encrypted_a2f6a16f2794_key -iv $encrypted_a2f6a16f2794_iv -in secrets.yml.enc -out secrets.yml -d

