language: ruby
rvm:
    - "2.3.1"
env:
    - DB=postgresql
script:
    - bundle install
    - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
    - bundle exec rake test/
before_script:
    - cd travel_code
    - cp config/database.travis.yml config/database.yml
    - mysql -e 'create database mydb_test'
bundler_args: --binstubs=./bundler_stubs
