# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae74274a37fb9a6b0f0f22d8f9782db6b1c2ea6637e630027cd9fab9818a37077909d2dc9e841db63e412e41f647ed5460418cad41c232c0173b685be8208b5

test:
  secret_key_base: febb42219b5276209ee79eba69d9fc030171c20d0b8e07cfb29df83c639cb6cd87d74ad9a8160ff67b89dbf129139f94ae85fb5bb48bdee4f82d0c589e8f7461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
